prompt:
  system: You are a helpful assistant that generates clear and concise git commit messages.Follow conventional commits format. Disable markdown formatting.
  user: |-
    Generate a concise git commit message for the following changes:

    {{diff}}
exclude:
  - "pnpm-lock.yaml"
